### ISSUE TITLE
First-time Windows Install, lein returns with "Error: Could not find or load main class clojure.main"

### ISSUE THREAD

**Issue by dmaas** [technomancy/leiningen#1282]
First-time Windows Install, lein returns with "Error: Could not find or load main class clojure.main"

Is this a classpath error? But I thought the Windows installer would take care of that?

**Comment by dplefevre** [comment]
Hi, I am new here and I can see that this is from a couple years ago, but I am getting the same issue "Could not find or load main class clojure.main." I've tried reinstalling several times, and the file which the other person referenced doesn't seem to be there any more. Any help?

**Comment by winks** [comment]
@dplefevre 

Are you sure you downloaded [the latest version](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat)? The version string is kind of hardcoded in there.
If you run `lein.bat self-install` it should download the JAR. The aforementioned file is a 2 year old version, that's why the link is dead.
