### ISSUE TITLE
REPL: Connection Refused in OSX

### ISSUE THREAD

**Issue by kurtismullins** [technomancy/leiningen#1321]
I've recently tried to use Leiningen and the repl on my Mac. I had to downgrade to 2.1.2 to have any success.

At this point, I have only tried 2.3.2 (latest), 2.3.1, and 2.1.2.

In a nutshell, when I run `lein repl`, I get the following output:

``` bash
localhost:~ kurtis$ rm -rf ~/.lein/ ~/.m2/
localhost:~ kurtis$ lein repl
Downloading Leiningen to /Users/kurtis/.lein/self-installs/leiningen-2.3.2-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.1M  100 13.1M    0     0   246k      0  0:00:54  0:00:54 --:--:--  224k
Retrieving org/clojure/tools.nrepl/0.2.3/tools.nrepl-0.2.3.pom from central
Retrieving org/clojure/pom.contrib/0.1.2/pom.contrib-0.1.2.pom from central
Retrieving org/sonatype/oss/oss-parent/7/oss-parent-7.pom from central
Retrieving clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.pom from clojars
Retrieving org/clojure/tools.nrepl/0.2.3/tools.nrepl-0.2.3.jar from central
Retrieving clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.jar from clojars
nREPL server started on port 51327 on host 127.0.0.1
ConnectException Connection refused
    java.net.PlainSocketImpl.socketConnect (PlainSocketImpl.java:-2)
    java.net.PlainSocketImpl.doConnect (PlainSocketImpl.java:382)
    java.net.PlainSocketImpl.connectToAddress (PlainSocketImpl.java:241)
    java.net.PlainSocketImpl.connect (PlainSocketImpl.java:228)
    java.net.SocksSocketImpl.connect (SocksSocketImpl.java:431)
    java.net.Socket.connect (Socket.java:527)
    java.net.Socket.connect (Socket.java:476)
    java.net.Socket.<init> (Socket.java:373)
    java.net.Socket.<init> (Socket.java:187)
    clojure.tools.nrepl/connect (nrepl.clj:184)
    clojure.core/apply (core.clj:617)
    clojure.tools.nrepl/add-socket-connect-method!/fn--3297 (nrepl.clj:226)
Bye for now!localhost:~ kurtis$
```

In 2.1.2, it works. Here is my success output and version information:

``` bash
localhost:~ kurtis$ lein repl
nREPL server started on port 51437
REPL-y 0.1.10
Clojure 1.5.1
    Exit: Control+D or (exit) or (quit)
Commands: (user/help)
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
          (user/sourcery function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
Examples from clojuredocs.org: [clojuredocs or cdoc]
          (user/clojuredocs name-here)
          (user/clojuredocs "ns-here" "name-here")
user=> exit
Bye for now!

localhost:~ kurtis$ lein --version
Leiningen 2.1.2 on Java 1.6.0_51 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by bjeanes** [comment]
I randomly started having this error this morning. Turning wifi off did not work. `lein repl` outside of a project works fine, but inside this specific project it does not. (Re-)setting hostname did not work. Specifying `:host` did not work. This leads me to think it's something about the `project.clj` file.

After furiously commenting out everything, it seems like only removing `:eval-in :nrepl` did the trick. This is particularly, peculiar, because I've had that present since the beginning of this project, so I'm assuming it was some interaction between that option and something else. 

Even more confusingly, after putting that option *back*, `lein repl` continues to work now. However, I did also `rm -rf target/` before adding it back (but after removing it and successfully getting a REPL). So I am left believing that somehow some stale artefact of some kind was interacting with `:eval-in nrepl` in a poor manner.

@technomancy, any idea what that might be?

**Comment by technomancy** [comment]
Yeah... that kind of makes sense actually. You told Leiningen that you
wanted to get it to eval all code in an existing process over nrepl, if
such a process was available. The way it determines whether it's
available is by looking for the port file, so it can tell how to
connect; if the port file does not exist, then :eval-in :nrepl becomes a
no-op. Unfortunately there is no checking for the case in which the port
file exists, but the process it's pointing to has been killed. Happy to
take a patch for this; it is in the eval-in multimethod in eval.clj of leiningen-core.

Arguably the silent fallback of :eval-in :nrepl to :eval-in :subprocess
is a mistake; perhaps it should at least emit a warning that it couldn't
find the nrepl server and that it's falling back?

On a side note, putting :eval-in :nrepl in project.clj doesn't really
make any sense in most cases; it is intended as a user-level
setting. Just because you like to keep an nrepl server running to save
time doesn't mean that everyone else on your team will.

**Comment by bjeanes** [comment]
> for the case in which the port file exists

I definitely removed the `.nrepl-port` file so I don't think it was that...

> On a side note, putting :eval-in :nrepl in project.clj doesn't really
make any sense in most cases; it is intended as a user-level
setting.

Good to know. I've removed it now anyhow...

**Comment by technomancy** [comment]
> I definitely removed the .nrepl-port file so I don't think it was that...

Hm; that's my only hypothesis... not sure what's going on otherwise. But in any case the bug I described definitely exists and causes these symptoms, so maybe others who are affected are hitting it.

**Comment by bjeanes** [comment]
If I experience it again I'll `cp` the entire directory aside before experimenting and see if I can reduce it to a minimum example before trashing `target` to test workaround.

**Comment by ilmoraunio** [comment]
Same problem as with @bjeanes, except turning off wifi did not help. Tried `lein repl :start :host 0.0.0.0` without success. Repl worked outside of project but not inside. Deleted `target` folder and repl started working inside the project again.

**Comment by danemacaulay** [comment]
Have the same problem, able to work around by running a headless repl, then connecting to it in another shell

    > lein repl :headless
    nREPL server started on port 9991 on host 127.0.0.1 - nrepl://127.0.0.1:9991`

then in another shell

    > lein repl :connect nrepl://127.0.0.1:9991

**Comment by kumasento** [comment]
Same issue on OS X 10.11.1 with the latest leiningen version and Java 8

```
➜  ~  lein version
Leiningen 2.5.3 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM
➜  ~  lein repl
Exception in thread "main" java.net.ConnectException: Connection refused, compiling:(/private/var/folders/51/ltyt5w153533rynjvf1qwhdm0000gn/T/form-init132623065674617613.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at clojure.tools.nrepl$connect.doInvoke(nrepl.clj:184)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.tools.nrepl.ack$send_ack.invoke(ack.clj:47)
	at clojure.tools.nrepl.server$start_server.doInvoke(server.clj:157)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at user$eval1117.invoke(form-init132623065674617613.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
```

This problem could be resolved by @danemacaulay 's solution.

**Comment by agarman** [comment]
Also getting same issue again.

**Comment by hyPiRion** [comment]
I'm reopening this. Although there are workarounds, this seems to be a pain point for users. Patches reducing the occurrence of this would be welcome.

**Comment by BinitaBharati** [comment]
I was facing the same issue with the following configuration :
`Leiningen 2.9.0 on Java 1.8.0_201 Java HotSpot(TM) 64-Bit Server VM`

I had this setting in my project.clj : `:repl-options {:host "192.168.10.12" :port 42676}`

To start the repl successfully on the IP other than localhost's , I had to run the repl just as specified by @danemacaulay. That is, I ran `lein repl :headless` which gave the following output :
 `Listening for transport dt_socket at address: 5010`
  `nREPL server started on port 42676 on host 192.168.10.12 - nrepl://192.168.10.12:42676`. 
After that I was successfully able to connect to the this repl as `nrepl://192.168.10.12:42676`

**Comment by technomancy** [comment]
From reading the responses here it seems like this is a firewall issue. I'm not sure what we can do here to work around issues if the user has set up a firewall but hasn't set up exclusions for this, other than defaulting to domain sockets or something, but that's a different topic altogether.

I can reopen this if there are actionable suggestions but at present it appears we have nothing.
