### ISSUE TITLE
potemkin throws ExceptionInitializerError on deploy

### ISSUE THREAD

**Issue by technomancy** [technomancy/leiningen#1693]
https://gist.github.com/technomancy/ca0c5422b63c1f89dd3d

Not sure what's going on here, but ideally we could remove the potemkin dependency.

**Comment by hyPiRion** [comment]
I've experienced this lately with `bin/lein test`, but with complaints on not finding `clojure.lang.PersistentUnrolledVector` (found in clj-tuple, which potemkin depends on). We may have some transitive version range dependency that dies because clj-http gets to decide on an older version of potemkin. I decided to pin it, hopefully this issue will be resolved as well.

**Comment by hyPiRion** [comment]
I am unable to reproduce this now, so I'm guessing most of this would be related to bumping clj-http (#1959) and/or figure out what we need to do with potemkin.
