### ISSUE TITLE
tools.nrepl not included in uberjar if it is a transitive dependency

### ISSUE THREAD

**Issue by cprice404** [technomancy/leiningen#1762]
If I have `tools.nrepl` listed as a first-class dependency in a project.clj file, and I run `lein uberjar`, I see the nrepl code included in the jar.  However, if it is a transitive dependency that comes in via another project, it does not get included in the uberjar.

**Comment by hyPiRion** [comment]
This could be caused by the same issue that caused trptcolin/reply#162 – that is, the latter version is compiled/installed with 2.5.1, which makes the nrepl dependency go into the test scope. Now, regardless of Lein version, the dependency won't be brought in.

**Comment by hyPiRion** [comment]
@cprice404: Could you upgrade to 2.5.2 and see if the problem still persists? It should in theory be fixed there.

If not, could you attempt to create a minimal example that reproduces this bug?

**Comment by timvisher** [comment]
fwiw, I was experiencing behavior very similar to this but it wasn't because the transitive dep wasn't brought in, it was because tools.nrepl wasn't brought in at all by my code and was instead brought in by a third-party jar that wasn't included in the uberjar profiles. In my case, the misunderstanding was thinking that cider-nrepl depended on tools.nrepl, which it does not.

It's also very confusing to people (at least where I work) that leiningen will by default add tools.nrepl to your project dependencies but won't add it during an uberjar. This is sensical but surprising behavior. :)

I now include tools.nrepl using 2.5.2 as a transitive dependency and it works perfectly.

**Comment by hyPiRion** [comment]
Alright, I'll consider this resolved then. Feel free to reopen if you can still reproduce it in some way.

**Comment by cprice404** [comment]
@hyPiRion a co-worker just brought this to my attention; no idea how I missed your ping a few months ago.  But my co-worker confirms that 2.5.2 fixes this for him.
