### ISSUE TITLE
LEIN_HOME

### ISSUE THREAD

**Issue by yantonov** [technomancy/leiningen#1820]
Why LEIN_HOME maps by default to $HOME/.lein instead of lein install path ? 
Comparing to maven M2_HOME (same as JAVA_HOME) - maven install path not maven local repo $HOME/.m2. Of course its just name convention, but there is a probability to use it as install path and got problem with profiles.clj for example.

**Comment by technomancy** [comment]
I'm not sure what you mean. This is just how dotfiles work. The install path of the `lein` script is up to the user and cannot be predicted in advance. On many systems it is in a location that is not writeable. The user config files must live inside the home directory because they're owned by the user.

**Comment by yantonov** [comment]
Accidentally i use LEIN_HOME var as install path to lein script (~/Development/bin/lein) and add this path into $PATH var. Thats why i cant use profiles.clj (because of its default location $HOME/.lein/profiles.clj). Of course, this is rare and personal situation and as you notice 'cannot be predicted'.
Thanks !
