### ISSUE TITLE
How to run directly without any associated alias?

### ISSUE THREAD

**Issue by binarykitchen** [technomancy/leiningen#1844]
Hello again

I have this configuration here:

```
  :aliases
  {
    "run"         ["do" ["shell" "gulp"] "run"]
    "jar"         ["do" ["shell" "gulp"] "jar"]
    "uberjar"     ["do" ["shell" "gulp"] "uberjar"]
    "redline-rpm" ["do" ["shell" "gulp"] "redline-rpm"]
    "release"     ["do" ["shell" "gulp"] "release"]

    "dev"   ["pdo" "run" ["shell" "gulp-dev" "watch"]]
    "test"  ["shell" "gulp" "test"]

    "deps"  ["do" "deps" ["npm" "prune"]]
  }

  :shell
  {:commands
    {
      "gulp"     {:default-command "node_modules/.bin/gulp"}
      "gulp-dev" {:default-command "node_modules/.bin/gulp" :env {"DEV" "true"}}
    }
  }
```

You see that I am running gulp first for some commands. But the problem is within the `dev` alias, where I call `run` together with `gulp-dev` whereas the `run` will trigger the `run` alias which will run gulp.

How can I call `run` inside the `dev` alias without the associated alias?

**Comment by hyPiRion** [comment]
I think the easiest is to just name the run alias something else :)

But considering you're doing a lot of repeated work for each task, maybe you should have a look at `:prep-tasks` and profile merging (`with-profile`). The [profiles documentation](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md#merging) has some notes on how you could potentially do it.

**Comment by binarykitchen** [comment]
Naming the run alias to something else won't solve it because I want to run Gulp tasks before `lein run`. But when running in development mode, i.E. with `lein dev` I want to run different Gulp tasks before `lein run`. That's the problem.

I cannot use `:prep-tasks` to solve this because they are always executed, no matter what lein command you are picking.

(profiles, nice but that would add more complexity which we want to avoid)

**Comment by hyPiRion** [comment]
I'll see if there's any way to do this with pure lein, but it's not on my top priority right now. I'll keep it open though, as it's probably enough interest to find a general solution to something like this.

**Comment by jvandyke** [comment]
@binarykitchen You probably figured this out already, but to anyone else who comes across this the answer is in the `do` syntax. You must separate the tasks to want to run in an alias with a comma. Like so from command line:

    $ lein do shell gulp, jar

But of course, Clojure arrays don't care about commas, so the comma must be added inside the quotes. In an example where you want to run `lein shell gulp` then `lein jar` you'd write:

````clojure
:aliases {
  jar ["do" "shell" "gulp," "jar"]
}
````

The `do` task documentation is very sparse, but here's what I could find: https://github.com/technomancy/leiningen#basic-usage

**Comment by binarykitchen** [comment]
thx, this is good, works for me (yes, have figured that out)

**Comment by darwin** [comment]
Today I wanted to do a similar thing. My problem is the checkouts feature. I have to run `lein jar`, `lein install`, `lein uberjar` (and similar) without checkouts directory if present (checkout projects are causing troubles in my own project.clj because their lein plugins get automatically included in my project). I wish I could disable it on per-profile basis, but unfortunately Iein does not have such an option. So I wanted to define aliases which would wrap lein invocation with a simple bash script, which would move checkout out and then move it back. But I hit this same issue of 'How to invoke original task without aliases being applied?'

Fortunately turns out there exists a solution using `:profiles` and `lein-shell` plugin for the price of nested lein invocation (which I'm willing to pay):

``` clojure
:profiles {:nuke-aliases {:aliases ^:replace {}}}
```

``` clojure
:plugins [[lein-shell "0.4.2"]]
:aliases { jar ["shell" "scripts/lein-without-checkouts.sh" "jar"] }
```

where `scripts/lein-without-checkouts.sh` does something like this:
``` bash
lein with-profile "+nuke-aliases" "$@"
```

The actual script is here: https://github.com/binaryage/dirac/blob/master/scripts/lein-without-checkouts.sh

**Comment by technomancy** [comment]
It sounds like we have a solution for this.
