### ISSUE TITLE
Help/guide user in the event of an ultimate failure

### ISSUE THREAD

**Issue by katarinahallberg** [technomancy/leiningen#1883]
It would be helpful to get some guidance on what to try/look for when a lein task fails.

Using: 

```
$ lein version
Leiningen 2.5.1 on Java 1.8.0 Java HotSpot(TM) 64-Bit Server VM
```

I had problem when running:

```
lein new app
```

All I got was a long stack trace with the exception clojure.lang.ArityException: Wrong number of args (1) passed to: cache/lru-cache-factory.

See full stack trace at: https://gist.github.com/katarinahallberg/c33165101db18fee1a8a

Enabling debug with

```
$ export DEBUG=true
```

revealed the classpath: _/Users/katarinahallberg/tools/grinder-3.11/lib/grinder.jar::/Users/katarinahallberg/.lein/self-installs/leiningen-2.5.1-standalone.jar_

Removing grinder from classpath with

```
$ export CLASSPATH=
```

solved the issue. Grinder in the classpath caused a conflict with different versions of core.cache.

Would have been helpful with some suggestions on how to debug the issue to get to the solution quicker and easier.

**Comment by technomancy** [comment]
While I agree it would be great to offer users more guidance when things
fail, this particular problem is nearly impossible to detect.

The best fix I can think of would be to deprecate setting $CLASSPATH and
issue a warning if it's set, since it's nearly always a mistake.

Happy to entertain other suggestions if you have something specific.
