### ISSUE TITLE
Can I get some parameters of lein from my code when compiling?

### ISSUE THREAD

**Issue by gekailin** [technomancy/leiningen#1908]
Hello, I hope to distinguish whether it is compile time or run time in my code, and further I hope I can pass some parameters from the command line to my code, like this:

lein run/compile/uberjar param1=value1 param2=value2

Then I want to access param1, param2 and maybe some other parameters of leiningen (such as the name of current profile) from my code.

How could I fulfill this?

**Comment by technomancy** [comment]
gekailin <notifications@github.com> writes:

> Hello, I hope to distinguish whether it is compile time or run time in
> my code, and further I hope I can pass some parameters from the
> command line to my code, like this:
>
> lein run/compile/uberjar param1=value1 param2=value2
>
> Then I want to access param1, param2 and maybe some other parameters
> of leiningen (such as the name of current profile) from my code.

This is actually explicitly not supported by design. The goal is to
allow your code to work the same way whether it's running from inside
Leiningen or not, so placing Leiningen-specific code inside your
application is considered harmful.

Instead, try using profiles. You can activate the profiles which will
merge new maps into the project map, and if you really need to feed
things in at runtime, you can use system properties.

-Phil

**Comment by gekailin** [comment]
Thanks~

Can I know which profile is currently using in my code? Or can I access some parameters of the profile configuration?

**Comment by technomancy** [comment]
The profile name is not given (for the same reasons as those listed
above) but system properties are visible and can be specified as part of
a profile.

**Comment by hyPiRion** [comment]
I feel this is answered; you can do e.g.

```clj
:profiles {:mysetup {:jvm-opts ["-Dparam1=value1" "-Dparam2=value2"]}}
```

Doing `lein with-profile +mysetup uberjar` will now set those system property values during the uberjaring.

Feel free to reopen if there's still some confusion around this.

**Comment by gekailin** [comment]
Thanks very much !
