### ISSUE TITLE
Why don't lein test add failed test details to some file?

### ISSUE THREAD

**Issue by shalu214patil** [technomancy/leiningen#1924]
When there is some failure, lein test adds failed test's ns name to the .lein-failure. Basically that is used by retest plugin. But, we need to run only failed tests and so that want failed test details as well. Why this is not done yet? I mean data is available, can we do this?

**Comment by technomancy** [comment]
If I recall correctly, the file currently contains a set of failures. Replacing this with a map of namespaces to failure details would probably be a non-breaking change, so I think there shouldn't be any problem accepting a PR for this.

**Comment by shalu214patil** [comment]
retest plugin is dependent on ns names of the .lein-failure. Replacing that with test details will break retest plugin.

**Comment by shalu214patil** [comment]
yes, we can do this. But need to update retest plugin as well. Will add PR on both repos.

**Comment by technomancy** [comment]
You're right--I thought it would stay the same since maps and sets both function similarly when checked for the presence of an entry, but the retest task only treats it as a seq, which sets and maps act differently as.

BTW the lein-retest plugin is deprecated; it has been merged into Leiningen itself now, so as long as the retest task is updated we should be good.

**Comment by shalu214patil** [comment]
I have sent PR - https://github.com/technomancy/leiningen/pull/1933. Please review it. Thanks.

**Comment by hyPiRion** [comment]
Implemented by #1933.
