### ISSUE TITLE
Overriding nREPL version doesn't work in projects with :eval-in-leiningen true

### ISSUE THREAD

**Issue by alexander-yakushev** [technomancy/leiningen#1939]
When working on a Leiningen plugin that has `:eval-in-leiningen true` in CIDER, `lein repl` uses very old embedded version of nREPL instead the one provided in `:dependencies`.

A temporary solution to this is to disable `:eval-in-leiningen` and add Leiningen dependency to `:dependencies`.

**Comment by technomancy** [comment]
The problem here is that Leiningen's version of nrepl is on the bootclasspath, and my understanding of `clojure.core/require` is that it will always prefer content on the bootclasspath to any other content. I don't think this is fixable without taking Leiningen off the bootclasspath, which will dramatically increase boot time.
