### ISSUE TITLE
EC2 IAM Role Support?

### ISSUE THREAD

**Issue by timvisher** [technomancy/leiningen#1953]
EC2 instances can have IAM roles that are available via their metadata which basically allows tools that require access to AWS apis to work by virtue of being on a certain EC2 instance.

Is support for this in the pipeline for lein/already present?

**Comment by technomancy** [comment]
Can you describe how Leiningen would use such a feature? I don't understand how they are connected.

**Comment by timvisher** [comment]
Oh LOL. I completely forgot that s3 wagon _isn't_ lein. :) There's already [an issue](https://github.com/technomancy/s3-wagon-private/issues/18) over there to support these.

I suppose I'm thinking mainly of the deploy task, which still references either GPG encrypted credentials or environmental credentials?

**Comment by technomancy** [comment]
Oh, I see. Yes, that would make plenty of sense for credentials. If you
take a look at how this is implemented, if it can be done in a plugin
that would be ideal since this is a pretty rare use case.

However, at a glance I'm not seeing a way to do that easily. I would
like it if we made leiningen.core.user/resolve-credential into a
multimethod that could be configured to load its defmethod out of a
plugin, similar to the way you can configure :middleware with a
namespaced keyword that requires the namespace of the keyword... does
that make sense? (See leiningen.core.utils/require-resolve.)

**Comment by memory** [comment]
Relevant: https://github.com/technomancy/leiningen/pull/1990

**Comment by hyPiRion** [comment]
Should be resolved by #1990.
