### ISSUE TITLE
Leiningen Bug In Producing Uberjars Or Misunderstanding?

### ISSUE THREAD

**Issue by w33tmaricich** [technomancy/leiningen#1965]
Ripping this question/bug straight from http://stackoverflow.com/questions/31197792/leiningen-bug-in-producing-uberjars-or-misunderstanding

What can cause lein uberjar to fail with "Caused by: java.lang.ClassNotFoundException" errors when lein run runs my app successfully? I'm using leiningen 2.5.1.

It looks like leiningen provides profiles as a way to make custom environments for certain tasks. However, I don't believe a profile difference between what is happening with lein run and lein uberjar is responsible because ...

1) I tried producing the uberjar with every possible profile, via lein with-profile <profile> for every <profile> named in the output of lein show-profiles.

2) I ran lein with-profile uberjar run, and no errors arose.

In case the answer to this problem and similar problems might be specific to the classes and dependencies involved, it is classes related to Overtone that produce the ClassNoteFoundException errors.

My project.clj file looks like:

```clojure
(defproject proj-name "0.1.0-SNAPSHOT"
  :description "project description"
  :url "http://github.com/mygithub/url.git"
  :license {:name "GPL v3"
            :url "http://www.gnu.org/copyleft/gpl.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                            [org.clojure/data.json "0.2.6"]
                            [org.apache.commons/commons-daemon "1.0.9"]]
  :main proj-name.core
  :target-path "target/%s"
  :resource-paths ["resources/spread.jar"
                             "resources/RTAClient.jar"
                             "resources/log4j-api-2.0-beta8.jar"
                             "resources/log4j-core-2.0-beta8.jar"]
  :profiles {:dev {:aot :all}
                 :uberjar {:aot :all}})
```

**Comment by hyPiRion** [comment]
I'm guessing the jars you have on your `:resource-paths` are libraries you depend on. Instead of putting dependencies on the resource path, put them in the `:dependencies` vector instead. The last two resources would be `[org.apache.logging.log4j/log4j-api "2.0-beta8"]` and `[org.apache.logging.log4j/log4j-core "2.0-beta8"]`.

If they are free-floating jars, have a look here: https://github.com/technomancy/leiningen/wiki/Repeatability#free-floating-jars. http://stackoverflow.com/questions/19496263/how-do-i-use-checked-in-jars-with-leiningen/19498585#19498585 may also be of help.
