### ISSUE TITLE
Nonexisting resource and source directories are created when invoking lein

### ISSUE THREAD

**Issue by maxp** [technomancy/leiningen#2010]
lein new default app1; cd app1; lein repl;
ls "dev-resources"

**Comment by bjconlan** [comment]
Yeah, I did a quick look over the source to see if changing the following would work:

`:profile {:dev {:resource-paths []}}`
`:dev-resources-path ""`
`:dev-resources-path nil`
`:dev-resources-path []`
(the later 2 (expectedly) throw exceptions due to unexpected types).

I think perhaps this folder should be created when flagged in the `project.clj` as opposed to by default (that way we can stop it from being conj'ed onto the `:resource-paths` vec) and stop the folder from being created.

**Comment by mvitz** [comment]
Maybe it helps:
This bug was introduced by 1ecbb98ffcc843320b2c937537855b652e9d0242

**Comment by hyPiRion** [comment]
Oh, I forgot about that one. I'm not sure we can revert the fix in #1974 as it's essentially fixing a very subtle and annoying bug. And removing `dev-resources` would cause an avalanche of bug reports, so I'd not do that immediately either.

Would it be possible to have a deprecation warning about `dev-resources` if it exists and is nonempty, and you don't explicitly refer to it in any profile?

**Comment by maxp** [comment]
As I understand now lein handles `dev-resources` for compatibility with old versions, right?
Is it possible to do that only for `:min-lein-version` less than 2.5.3 for example?

That would be compatible with old setup.

**Comment by hyPiRion** [comment]
Yeah, that could be doable I guess.

**Comment by hiredman** [comment]
the correct behavior is for `lein new` to create the directories when creating a new project. then the directories can be deleted and not endlessly re-created whenever lein is run.

**Comment by hyPiRion** [comment]
@weavejester: Is #1974 a major issue, or is it only a problem after e.g. lein clean or a fresh checkout of the project? Since there's some discussion back and forth, I was wondering whether this could be solved in a different way (without too much work for plugin-devs).

**Comment by weavejester** [comment]
If all the directories are created then it's not an issue, but these are directories that are frequently outside of source control. At best it's frustrating to start up a REPL only to have to shut it down again because some classpath directories are not created. At worst it's an error that's hard to diagnose unless you're already familiar with the problem.

Could we limit the directories created to just those that should be explicitly created? So `:source-paths`, `:resource-paths`, `:test-paths`, etc. If the `dev-resources` path cannot be specified or cleared, it makes sense that we shouldn't automatically create it. But if a user explicitly specifies something in their project file to be used as a classpath, then Leiningen should probably ensure that directory exists.

**Comment by hyPiRion** [comment]
I've implemented this so that implicit resource directories are not created. Explicit directories will still be created like in 2.5.3.

**Comment by maxp** [comment]
Great.
