### ISSUE TITLE
Doesn't ignore Emacs' temp files

### ISSUE THREAD

**Issue by zilti** [technomancy/leiningen#2048]
Leiningen doesn't ingore hidden temporary files Emacs creates. No matter if I have a running REPL, or try "lein midje autotest", when I edit a file and leave it unsaved for a couple of seconds I get bombarded with FileNotFound-errors due to the temp files. 
Is there a workaround? I remember this being an issue about two years ago, and I took a little break of a few months from programming, and now I have it again.

**Comment by hyPiRion** [comment]
The only workaround I know of as of now is to disable temporary files or place them in another location – I don't do it myself though, but that's because I usually use some other way to retest.

I am guessing files starting with `.#` aren't legal Clojure(Script) files, right? If Leiningen assumes those are legal, it would be nice to have a fix that filters those out.

**Comment by glts** [comment]
Passing by … I don’t think this is any of Leiningen’s business. Whatever editor (or other tool) you use, be prepared to configure it such that it does not interact in a bad way with whatever application you are working on.

**Comment by danielcompton** [comment]
This seems to be an issue for [lein-midje](https://github.com/marick/lein-midje) to address, not Leiningen, as lein-midge is the one doing the autowatching via [`midje.repl/autotest`](https://github.com/marick/Midje/blob/master/src/midje/repl.clj).

I'll close this for now, but could reopen if I've misunderstood?
