### ISSUE TITLE
release task should be a transaction

### ISSUE THREAD

**Issue by sertel** [technomancy/leiningen#2064]
When running `lein release` several steps are performed that are listed here:
https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md

When either of these steps fails then changes should be reverted. Per definition a release call was only successful when the jars were successfully deployed to the repo, say Clojars.

Changes to be undone include:
1. Revert the last commit that changed the version in the `project.clj` file. (via a combination of `git log`, `grep` and `git revert`)
2. Delete the tag that was created for this release. (`git tag -d`)

In order to do so, the release task should not be started if there are pending changes in the project repo. (Maybe it is already checking for that.)

**Comment by hyPiRion** [comment]
I agree in principle, but I'm not sure if this is feasible or even possible to do in practice.

Since you can [configure your own release tasks](https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#overriding-the-default-release-tasks), you can place `["deploy"]` as a step that is not the last one. It's not possible to revert a `["deploy"]`, so what do you do if something fails after a deploy?

The more problematic issue is that you can call whatever you want in `:release-tasks` before deploying. Leiningen has no idea how one can revert those things, or if it's even possible.

**Comment by sertel** [comment]
Then maybe it is the best to allow to specify undo actions per action in the release task.

**Comment by hyPiRion** [comment]
If we can find a way that makes this easy to do, then maybe I would consider it. However, it's not high on my list as many parts of deploy tasks are nonreversible.

**Comment by technomancy** [comment]
> In order to do so, the release task should not be started if there are pending changes in the project repo.

Yeah, the first step is `vcs assert-committed` so we're already doing that. I don't think it's a good idea to claim to be transactional here because we can't really guarantee that all the side-effects are rolled back, and the VCS-based side-effects should be clear enough.
