### ISSUE TITLE
Add plugins and dependencies from the command line

### ISSUE THREAD

**Issue by phillord** [technomancy/leiningen#2074]
Is there a way, or could a way be added to enable injecting plugins or dependencies into the leiningen from the command line, as opposed to having to modify profiles.clj.

I ask, because this would enable cider and other tools to run leiningen with the correct middleware without the users having to fiddle with their profiles.clj. This would substantially ease the installation of cider in the first place and well as easing updates. 

For myself, I also switch between versions of Emacs and cider, sometimes forward (to snapshot) and sometimes backward (to stable). So editing my profiles.clj constantly is painful.

**Comment by phillord** [comment]
Never mind. The update-in task does the job.

**Comment by hyPiRion** [comment]
Yeah – For CIDER, I guess `update-in` would be the go-to way to do it if you want to work with multiple versions.

**Comment by phillord** [comment]
The idea is also to reduce the initial installation burden. If cider can do it all without using profile.clj, then this will make life significantly better for newbies. update-in seems to do the job even if it does make the actual command line fairly long!

**Comment by hyPiRion** [comment]
@phillord Right – I see this fairly often when people want to have plugins they want to apply on a global level which is only used for your personal development environment. I'd be happy to hear ideas on how to make this distinction clearer, and support easier installation of these. The only thing that I don't want is to make it too magical for users.

For CIDER in particular though, I think we can make it easier on users to install right now. I'll pop up a suggestion in a PR in a moment.

**Comment by phillord** [comment]
I'm not sure that this is the correct solution. It still causes problems when moving backward and forward between versions. And as the boot folks have noted it means that the cider middleware will be installed for ANY repl not just those launched by cider. Update-in works and it's very constrainted.

I was working on a leiningen patch which allows adding an additional profile.clj file to be given on the command line (https://github.com/phillord/leiningen/tree/feature/extra-profile but unfinished). The simplest thing might be a task "merge-in" which would work like:

    lein merge-in $(CIDER)/cider-profile.clj repl

The update-in task is fine for changing one value but clunky for changing several.

**Comment by phillord** [comment]
Perhaps, we should re-open this! I think update-in is a nice solution for now. but perhaps there is something cleaner.

The discussion has been at https://github.com/clojure-emacs/cider/issues/1531

**Comment by phillord** [comment]
Also, with the PR you submitted this will still break after version upgrades. Of course repl.clj could be updated, but that assumes the user hasn't added anything. Still, it will have the advantage of breaking if anyone has a :repl profile in their profiles.clj already.

**Comment by hyPiRion** [comment]
Yeah, sounds sensible to reopen this. A merge-in task would make sense, at least for now. I am guessing it would be possible to compose with multiple tools as well if need be.

Some thoughts: Perhaps the name should be merge-profiles or something hairy like that, merge-in doesn't really tell you that profiles are being merged with the project map. And maybe the value should be the profiles to merge with, instead of the file with the contents. That would make it possible for CIDER to not refer to a file on disk. For others, that would just mean that they have to insert it like `lein merge-profiles $(<my-extra-profiles.clj) task`.

**Comment by phillord** [comment]
Easy on the name --  I am terrible at names anyway. Putting the value on the command line seems reasonable, unless the command line gets too long.

Anything that avoids the multiple update-in calls which are fairly ugly.

**Comment by glts** [comment]
The discussion above was about CIDER and nREPL – in the meantime CIDER has learnt the ability to inject nREPL middleware and will do so automatically, see https://docs.cider.mx/en/stable/installation/#ciders-nrepl-middleware.

So that point has been resolved. If there is still more to do here, clarification or adjustment of the goals is appreciated.

**Comment by technomancy** [comment]
If folks are still interested in pushing this forward it can be done in a plugin first, then potentially submitted to Leiningen once it stabilizes and has proven itself.
