### ISSUE TITLE
Classpath sometimes doesn't include all dependencies when using `lein trampoline`

### ISSUE THREAD

**Issue by mneise** [technomancy/leiningen#2095]
Running `lein-cljsbuild` with `lein trampoline` seems to behave inconsistently and sometimes doesn't include all required dependencies in the classpath. This issue has been initially reported in `lein-cljsbuild` (https://github.com/emezeske/lein-cljsbuild/issues/204).

Whenever we compile a ClojureScript project, we modify the project's dependencies to include the recent version of the support project `cljsbuild` and then pass the modified project config to `eval-in-project`. But running `lein trampoline do cljsbuild once dev, repl`, for example, doesn't seem to include `cljsbuild` in the classpath and therefore fails with a `FileNotFoundException` ([full stacktrace](https://gist.github.com/mneise/e5fbd3a3028138b7d4a6)). Whereas, running `lein trampoline do clean, cljsbuild once dev` works fine and `cljsbuild` will be included in the classpath.

I've created a minimal repository to reproduce this problem: https://github.com/mneise/cljsbuild-trampoline.

**Comment by hyPiRion** [comment]
Thanks for the report and the reproducible case =)

Trampoline is known to be a bit fragile with multiple tasks, perhaps especially when used in conjunction with plugins. I'll take a look when I got time on my hands, but would obviously be happy if others are interested in looking into this.

As a workaround, would it be sufficient to run `lein do cljsbuild once dev, trampoline repl`, or would that break things for you?

**Comment by mneise** [comment]
Yes, you are right, so far I was only able to reproduce this problem when using `trampoline` in conjunction with `do`. But then again, it doesn't fail for all cases, e.g. `lein trampoline do clean, cljsbuild once dev` works fine.

I think it's mostly causing problems for users when wanting to start a ClojureScript REPL with `lein-cljsbuild` in @cursive-ide. You're proposed workaround might be a good solution for this problem for now, or maybe @cursive-ide is already using this as a workaround?

**Comment by mmower** [comment]
Has there been a regression here? I'm having what appears to be the same problem that started when I couldn't run a `lein repl` from within Cursive. It turns out I can't run `lein trampoline repl` from the terminal either.

[project.clj.txt](https://github.com/technomancy/leiningen/files/810628/project.clj.txt)

Siona:carnivore matt$ lein trampoline repl
Compiling ClojureScript...
Exception in thread "main" java.io.FileNotFoundException: Could not locate cljsbuild/compiler__init.class or cljsbuild/compiler.clj on classpath., compiling:(/private/var/folders/dw/tmf07r7n1cv6khc7rc35q4cw0000gn/T/form-init6012428293632658123.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)

**Comment by technomancy** [comment]
> Whenever we compile a ClojureScript project, we modify the project's dependencies to include the recent version of the support project cljsbuild

As I understand it, this approach is fundamentally incompatible with `trampoline` since the latter requires the dependencies to be present after the Leiningen JVM has exited. If the compilation of the project requires dependencies to be on the classpath, they should be specified in `project.clj`, possibly in a profile.
