### ISSUE TITLE
:aot with :prep-tasks does not compile namespaces

### ISSUE THREAD

**Issue by vadali** [technomancy/leiningen#2129]
Hey,
If I have `:prep-tasks` key in my project.clj along with `:aot` key, no namespaces are getting compiled:

```
:aot :all
:prep-tasks [] ;; yes, even an empty vector causes the problem!
```

and then:

```
> lein uberjar  
Created /home/user/work/proj/target/proj-0.1.0-SNAPSHOT.jar
Created /home/user/work/proj/target/proj-0.1.0-SNAPSHOT-standalone.jar
```

however, if I remove `:prep-tasks` at all, it works again:

```
> lein uberjar
Compiling 8 source files to /home/user/work/proj/target/classes
Compiling namespace.a
Compiling namespace.b
Created /home/user/work/proj/target/proj-0.1.0-SNAPSHOT.jar
Created /home/user/work/proj/target/proj-0.1.0-SNAPSHOT-standalone.jar
```

It doesnt matter if I manually specify the namespaces instead of using `:all`, it still does not work...

WDYT?

**Comment by vadali** [comment]
ok, I think I found a solution. It really needs to be documented somewhere though. 

if you have have `:prep-tasks` and want to include aot code in it as well, make sure to include the task `complile` too, eg:

```
:aot :all
:prep-tasks ["javac"
             "scalac"
             "compile"]
```

Is this the desired behavior? I totally expected the namespaces to compile..

Thanks,
Shlomi

**Comment by technomancy** [comment]
The `:aot` key is only used by the `compile` task, so if you configure it such that the task isn't run, it won't be used. The docs for `:prep-tasks` do note that they override the default behavior of `compile`. If you have a more specific wording for this to suggest that you think would be clearer, feel free to open a pull request.

**Comment by ataggart** [comment]
I just ran into a problem using `:prep-tasks` in a profile and found this issue.

>The docs for `:prep-tasks` do note that they override the default behavior of `compile`.

@technomancy Which docs are you referring to here?

Going by [PROFILES.md](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md#merging), and the example use of `^:replace`, I assumed standard merging rules would otherwise apply, i.e., concatenating the project's implicit/default value with the profile's value (like how it works with, say, `:repositories`). Instead the resulting project map (using `lein-pprint`) has only the profile's `:prep-tasks` value.

Note that when explicitly adding `:prep-tasks ["javac" "compile"]` to the top-level project map, the profile specific `:prep-tasks` _is_ concatenated! Maybe this is a bug?
