### ISSUE TITLE
`lein uberjar` does not respect :target-path, and deletes development target files

### ISSUE THREAD

**Issue by sdegutis** [technomancy/leiningen#2166]
**Steps:**

* `lein new hello-world`
* `cd hello-world`
* `mkdir tmp`
* Add `:target-path "tmp/target/%s/"` to `project.clj`
* `lein repl`
* Meanwhile, in another tab: `lein uberjar`

**Expected:**

After all these step, there should be two dirs under `tmp/target`:

- `base+system+user+dev`
- `uberjar`

**Actual:**

There's only `uberjar` now.

**Potential confusion on my part:**

I was setting `:target-path` because I wanted to be able to create a brand new uberjar (from non-stale classes) during development (meaning during either `lein run` or `lein repl`). Maybe that's not what this setting is for? In which case I'm back to square one figuring out how to do that, if it's even possible at all.

**Comment by sdegutis** [comment]
Justin Smith on IRC has logged his verification of this unexpected behavior:

https://gist.github.com/noisesmith/8487c8a806e135d1f478592e6c9b5bed

**Comment by cprice404** [comment]
I think that what you are observing is expected behavior, based on the default value of the `:auto-clean` setting: https://github.com/technomancy/leiningen/blob/49abe1108599a82d4bad6cfb40a320295f0ebd99/sample.project.clj#L390-L393

There is some discussion in #1642 and #1798 , but basically any task that ends up invoking `jar` is also going to invoke `clean`, which will wipe out everything in your target directory.  It seems like in your use case you might just want to change the auto-clean setting in your project to `false`.

**Comment by sdegutis** [comment]
@cprice404 Thanks. That sounds like it fixes half of it. Is it possible to clean just the `uberjar` target somehow?

**Comment by hyPiRion** [comment]
It doesn't sound like a bad idea to have `uberjar`/`jar` only clean the directory(/-ies) it's going to build in, but I believe this unfortunately is tricky to do properly. Plugins may add in extra directories into `:clean-targets` which are used for uberjar creation, and users may not use "%s" in their `:target-path`s.

**Comment by sdegutis** [comment]
Thanks. Solved.
