### ISSUE TITLE
lein does not specify Main-Class for app template

### ISSUE THREAD

**Issue by achikin** [technomancy/leiningen#2208]
```
~/src → lein new app wonderland
Generating a project called wonderland based on the 'app' template.
~/src → cd wonderland/
~/src/wonderland → lein jar
Warning: The Main-Class specified does not exist within the jar. It may not be executable as expected. A gen-class directive may be missing in the namespace which contains the main method.
Created /Users/achikin/src/wonderland/target/wonderland-0.1.0-SNAPSHOT.jar
```
```
~/src/wonderland → cat src/wonderland/core.clj
(ns wonderland.core
  (:gen-class))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!"))
```
Am I missing anything?

**Comment by hyPiRion** [comment]
Perhaps you intended to use `lein uberjar`? That would bundle all the dependencies and create a standalone version which is runnable.

I think it's pretty rare to use `jar` for standalone apps, because then you have to provide all dependencies (Clojure including) and the like yourself, in which case you're a real poweruser of Leiningen.

Perhaps we should add a "maybe you meant `uberjar`?" message when this happens?

**Comment by achikin** [comment]
`uberjar` did the job, thank you!
