### ISSUE TITLE
classifier option fails in 2.7.1

### ISSUE THREAD

**Issue by iku000888** [technomancy/leiningen#2212]
Works in 2.6.1
Works in 2.7.0
Fails in 2.7.1
Has anyone experienced this?

**Comment by hyPiRion** [comment]
So that we're on the same track: What do you mean by fails? Do you have a minimal set of steps I can use to check it out?

**Comment by cprice404** [comment]
I'm using `:classifier` in several places in my projects and haven't seen any issues with lein 2.7.x.  @hyPiRion if there is something broken there's a decent chance that it has something to do with my changes, so I'm happy to look into it.

@iku000888 if you can provide a reproducer I will check it out.

**Comment by rfkm** [comment]
(I'm a friend of @iku000888 and know the background.)

This doesn't relate to classifiers. The problem is the way to parse dependency vectors has been changed in #2207.
Some leiningen plugin assumes the second position of dependency vectors is always reserved for  a version number. 
For instance, lein-modules allows us to specify a keyword as a version that has a special meaning. 
The following code is taken from lein-modules' README.

```clojure
(defproject org.immutant/web "1.0.3-SNAPSHOT"
  :plugins [[lein-modules "0.3.11"]]
  :description "The web component"
  :dependencies [[org.immutant/core :version]
                 [ring/ring-servlet "_"]
                 [potemkin "0.3.4"]])
```

Lein 2.7.1 can't parse the above project because it recognizes `:version` as an option key, and it will throw the "No value supplied for key: :version" error.

So, the following code will be an error, of course. ("No value supplied for key: test")
```clojure
[org.example/foo :version :classifier "test"]
```

**Comment by hyPiRion** [comment]
Dang, that's something thing I did not expect, thanks for bringing this up.

**Comment by cprice404** [comment]
Ugh.

@hyPiRion what do you think?  I could change the code so that it:

1. pulls the 0th element from the vector as the artifact name,
2. pulls any number of `[keyword value]` tuples off of the end of the vector,
3. if there's anything left, check to see if it's `nil`,
   3a. if it's `nil`, use `nil`
   3b. if there's no value leftover at all from the dependency vector then presumably they omitted it, so use `nil`, and
   3c. otherwise there was some non-nil value left, so we should just keep it intact?

**Comment by cprice404** [comment]
@rfkm @iku000888 could you possibly test #2213 and see if that fixes your issue?

**Comment by iku000888** [comment]
@cprice404 I checked your branch against our project.clj and it works gracefully.

**Comment by cprice404** [comment]
@iku000888 great, thanks for testing it out.

**Comment by iku000888** [comment]
Thanks for taking care of this!

**Comment by jcrossley3** [comment]
lein-modules maintainer here. Just wanted to voice a quick thanks for this change. I always hated the fact that I had to stick a placeholder in for the versions of my dependencies, e.g. `[foo/bar "_"]`. With 2.7.2, I can just use `[foo/bar]` and the correct version will still come out of the parent's `:versions` map without requiring any changes to lein-modules itself. i love it when things "just work" like that. :)
