### ISSUE TITLE
No `.nrepl-port` created with `lein trampoline repl`

### ISSUE THREAD

**Issue by jeaye** [technomancy/leiningen#2224]
Howdy,

I've found that `lein repl` creates the `.nrepl-port` file, while `lein trampoline repl` does not. Both are creating the nREPL, it seems, but the latter version neither announces the port nor creates the associated file. Is this intentional? It's crippling `vim-fireplace`, since the port information is not readily available.

Thanks

**Comment by robbieh** [comment]
I see the same behavior. I also noticed that `trampline repl` starts REPL-y 0.3.5 while `repl` starts REPL-y 0.3.7.

**Comment by technomancy** [comment]
Leiningen uses nREPL during normal repl operation because it has to communicate between Leiningen's own process (which is connected to stdin) and the project process. When trampolining, Leiningen's own process has exited, so it skips the client/server setup entirely as it is unnecessary.

If you explicitly want to start a server, you should be able to use `lein trampoline repl :headless`.

I will improve the docstring to make this clearer.
