### ISSUE TITLE
2.8.0 release date? 

### ISSUE THREAD

**Issue by huima** [technomancy/leiningen#2269]
Related to issues with Cheshire and AWS SDK ( see https://github.com/technomancy/leiningen/issues/2215 ) versions, would be interested to know when next release is intended to be made.

**Comment by technomancy** [comment]
I would like to wait to release 2.7.2 after Clojure 1.9 is out so that plugins can use it; however I don't know if it's a good idea to wait since it's been in alpha for an incredibly long time with (as far as I know) no indication a release is imminent. So maybe that's unrealistic.

I do have one more change I would like to land before a release, and that is moving the `reply` dependency to one that resolves at runtime so that we can avoid conflicts like this in the future.

**Comment by lkonstantinov** [comment]
Please, think of us, the poor victims of #2212 as well :)

**Comment by technomancy** [comment]
Also need https://github.com/technomancy/leiningen/pull/2261 resolved for 2.7.2.

**Comment by technomancy** [comment]
I would consider https://github.com/cemerick/pomegranate/pull/80 to be a blocker for 2.7.2 as well, since we are currently depending on an abandoned version of Aether.

**Comment by technomancy** [comment]
Since we're pulling in some bigger changes from a Maven upgrade off an unsupported version, I think the next version will be 2.8.0. We're also blocked on https://github.com/xeqi/pedantic/pull/1.

**Comment by technomancy** [comment]
We are very close to a 2.8.0 release; we need a non-alpha release of pomegranate and a decision about #2283, but it shouldn't be too far off now.

**Comment by glts** [comment]
Soon it will have been one year since the last Leiningen release.

We were close, but then the scope of 2.8.0 was expanded … Would it be a
possibility to cut a 2.8.0 soon and do the other issues in a follow-up
2.8.1?

**Comment by technomancy** [comment]
Yeah, I put a few things in the 2.8.0 milestone because they needed investigation, but upon looking into them further they shouldn't block the release. I changed it around and we're down to three open issues. One has an open PR that only needs a minor change, one is small and has someone volunteering to implement it, and one is entirely documentation.

Once the first two are taken care of I will create a release candidate. Hopefully that can happen before the end of this week.

**Comment by technomancy** [comment]
Release candidate 1 is out; you can try it with `lein upgrade 2.8.0-RC1`.

**Comment by technomancy** [comment]
Closed by 04b88e5, hurrah.

**Comment by glts** [comment]
Wonderful, thank you. That hurrah sounded a bit dejected … your work is
appreciated!
