### ISSUE TITLE
leiningen-standalone.jar manual installation or building from source

### ISSUE THREAD

**Issue by luhtonen** [technomancy/leiningen#2287]
I'm not able to install Leiningen on my work Windows machine. Installation command `lein self-install` is failing because our corporate firewall is blocking all ZIP files downloads.

To overcome this problem I need either a way of download pre-built leiningen-standalone.jar or build it from the source. I was trying to find an instruction how to do it without success.

**Comment by winks** [comment]
The easiest solution would probably be to just download the zip from GitHub to another server, rename it and manually put it into `%HOME%/.lein/self-installs/`. (There were some technical reasons at the time to host it as ZIP instead of JAR and renaming it, maybe those are lifted now, we could probably change that at some point, but not sure)

Building it yourself without an older/different version of lein is probably not possible - but the steps are here: https://github.com/technomancy/leiningen/blob/master/CONTRIBUTING.md#bootstrapping

The *proper* solution would be to try to persuade whoever is responsible for that mess that they're interfering with your work :P (I know, that usually doesn't work)

**Comment by luhtonen** [comment]
Here's workaround I come up with.
1. Downloaded `leiningen-2.7.1-standalone.zip` to my local machine
2. renamed this file to `leiningen-2.7.1-standalone.txt`
3. uploaded it to my GitLab project
4. from my corporate windows machine downloaded `txt` file
5. rename downloaded file back to `jar` file
6. moved this jar file to my `%USERPROFILE%\.lein\self-installs` directory (without extracting it)
7. create global profile file `%USERPROFILE%\.lein\profiles.clj` to setup corporate artifactory mirrors with the following content (I've removed actual urls):
```
{:user {:mirrors {"central" {:name "central" :url "<url to corporate artifactory>"}
                          #"clojars" {:name "Internal nexus" :url "<same url as above>" :repo-manager true}}}}
```

**Comment by pradeepanchan** [comment]
I faced an error and fixed it as follows:

OS: Windows 10 (64-bit)
My corporate proxy settings were set to "Auto-detect".

I faced an error when trying the usual "lein self-install" with the message "Unable to connect to the remote server". Suggestions from the lein.bat did not help. 

Then I went ahead and downloaded the installer. It too failed to download the "leiningen-2.8.1-standalone.zip" with the above message, but the installer didn't fail. It created the Clojure REPL shortcut under the "Leiningen" program group in the start-menu. Which obviously didn't work.

Then i followed the steps 1 to 6 mentioned by luhtonen and then fired up the Clojure REPL and it started to work :-)

**Comment by jholmgren** [comment]
Similar issue with 2.8.1 on Windows 10 
Before looking for a solution I performed the following:

Manually downloaded leiningen-VERSION-standalone .zip using feedback from lein self-install
Placed file in %USER%/.lein/self-installs directory
Modified line 31 in lein.bat to look for .zip not .jar
