### ISSUE TITLE
Received fatal alert: protocol_version

### ISSUE THREAD

**Issue by george-ayris** [technomancy/leiningen#2364]
Hi there

I've been trying to get started with leiningen and use it to start a project from a template and also install dependencies. However, I'm getting errors when a template or dependency is fetched e.g.

![image](https://user-images.githubusercontent.com/9038126/33343071-040d7850-d47c-11e7-8380-470f2237a741.png)

This is after a fresh install of leiningen 2.8.1 via Homebrew on OSX High Sierra 10.13.1. 

In this case the contents of `project.clj` are:
```
(defproject sample "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [clj-http "2.0.0"]])
```

Any help with what I'm doing wrong would be much appreciated.

**Comment by technomancy** [comment]
It sounds like you might have either an outdated TLS library or some
kind of network proxy interfering with your connections.

**Comment by orb** [comment]
I've gotten this `protocol_version` error on my Java 7 build machine with lein 2.8.x downloading from the new clojars.

Workarounds are: use java 8, downgrade to lein 2.7 or use  `LEIN_JVM_OPTS=-Dhttps.protocols=TLSv1.2`.

**Comment by george-ayris** [comment]
That has worked a charm! 

Thanks for your help, especially since I was confused because I thought I had Java 8 installed, but actually only had the JRE at Java 8, but not the JDK.

**Comment by orb** [comment]
Is Java 8 an actual requirement of Lein 2.8? I only see "version 8 is recommended at this time". Leiningen dependencies are completely broken in Java 7, (because of the clojars requirement of tls 1.2 only) so I don't see any reason to close this unless Java 7 is officially not supported anymore. (in which case, maybe we should update the docs to reflect this)

**Comment by technomancy** [comment]
According to https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html#SunJSSEProvider version 1.2 of TLS is supported by Java 7 but disabled by default for some reason. It sounds like we ought to take some steps to re-enable it.

For connections made by the built-in JDK classes this can be done with a simple system property, but this doesn't help for Clojars because it uses Apache HTTPClient: https://stackoverflow.com/questions/28391798/how-to-set-tls-version-on-apache-httpclient

Since we're using Apache HTTPClient indirectly thru pomegranate thru maven-aether, it's much more difficult to set this. Cursory searches show zero documentation for this, but I'll reopen to track this problem. I consider it a bug in the HTTP Wagon, but we should include a workaround anyway in Leiningen if possible.

**Comment by orb** [comment]
Just using `LEIN_JVM_OPTS=-Dhttps.protocols=TLSv1.2` works for me. I just tested on a fresh ubuntu box on digital ocean. With Java 7 and the latest lein, I can run lein and `lein new` just fine, but when I add a dependency from clojars, it fails. 

EX:

```
$ lein deps
Could not find artifact lightmod:lightmod:jar:1.1.0 in central (https://repo1.maven.org/maven2/)
Could not transfer artifact lightmod:lightmod:jar:1.1.0 from/to clojars (https://repo.clojars.org/): Received fatal alert: protocol_version
Could not transfer artifact lightmod:lightmod:pom:1.1.0 from/to clojars (https://repo.clojars.org/): Received fatal alert: protocol_version
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Error encountered performing task 'deps' with profile(s): 'base,system,user,provided,dev,update'
Could not resolve dependencies
```

Adding the the above property, everything works:

```
$ LEIN_JVM_OPTS=-Dhttps.protocols=TLSv1.2 lein -U deps
Retrieving lightmod/lightmod/1.1.0/lightmod-1.1.0.pom from clojars
...
```

I think for lein purposes, you'd want to add the other TLS versions and not just 1.2, but basically it does seem to work fine.

**Comment by tobias** [comment]
The reason this appeared in lein 2.8.x is we switched the default url that lein uses for clojars from `https://clojars.org/repo` (served by the clojars.org server) to `https://repo.clojars.org` (a CDN provided by Fastly). Unfortunately, Fastly only supports TLS 1.2. So another possible workaround until this is resolved is to use the old repo by overriding the url for clojars:

```
:repositories {"clojars" "https://clojars.org/repo"}
```

**Comment by technomancy** [comment]
Added a FAQ entry for this, but maybe it would be better to automatically either apply the system property or add a Clojars mirror for the non-CDN version when we detect we're running on an old JDK.

**Comment by danielcompton** [comment]
The PR for this switch was in https://github.com/technomancy/leiningen/pull/2225.

**Comment by technomancy** [comment]
Java 7 has been well past its end of life for quite some time now; closing this.

**Comment by hynnet** [comment]
jvisualvm -J-Dhttps.protocols=TLSv1.2

**Comment by hynnet** [comment]
解决 JDK1.7 下 jvisualvm  插件中心地址修改为新地址 https://visualvm.github.io/archive/uc/7u60/updates.xml.gz 后仍然报标题的错误。

启动命令加入参数： jvisualvm -J-Dhttps.protocols=TLSv1.2
