### ISSUE TITLE
When using an insecure HTTP repository, can't even view FAQ from command line

### ISSUE THREAD

**Issue by timmc-bcov** [technomancy/leiningen#2392]
```
$ lein deps :tree 
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.
```

OK, fair enough. Let's see that FAQ:

```
$ lein help faq
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.
```

🤔 

I think this is lein 2.8.1 but `lein version` also fails.

(Note that https://github.com/technomancy/leiningen/blob/master/doc/FAQ.md doesn't actually provide a way to work around this. I have to use an intranet repo that doesn't have TLS, and it's not my decision that it's insecure, so this forces me to downgrade lein.)

**Comment by technomancy** [comment]
The faq that ships with 2.8.1 explains the workaround, and I added it back to master. (Someone had told me it was broken, but it wasn't.) I don't have a good solution for how to allow the help task to run without downloading plugins though.

Maybe it would be better just to include a URL in the error message instead of pointing to the `help` task?

**Comment by timmc-bcov** [comment]
As much as I like the local documentation, I think this is a place where it's OK to just have a URL -- it should only happen for the first time when upgrading lein or adding a repo, and the user probably has an internet connection at that time.

**Comment by blak3mill3r** [comment]
```It's also possible you have a dependency which includes a reference to
an insecure repository for retrieving its own dependencies. If this
happens it is strongly recommended to add an `:exclusion` and report a
bug with the dependency which does this.
```

I am attempting to do so, but since `lein deps :tree` does not work, it is rather difficult to locate which transitive dependency is at fault. I suppose I will try doing so with an older `leiningen` version, IIUC this safety check was only added recently? between `2.7.1` and `2.8.1` ... is that correct?

**Comment by blak3mill3r** [comment]
I downgraded to `2.7.1` and now can launch a repl and `lein deps :tree` works, however the output of `lein deps :tree` does not show any `http` URLs (or indeed any `:repositories`). Any advice on how to proceed finding the offending dependency would be appreciated. I'm not sure how to begin looking... there are rather a lot of transitive deps and I don't know how to find which is using a public HTTP repository (or what else might be causing this error).

**Comment by blak3mill3r** [comment]
Ah, I discovered something interesting... I got the error message trying to start a repl using lein `2.8.1` *from an EC2 instance*, but using `2.8.1` locally I do not get the error message.

So perhaps this is not due to an insecure HTTP repository from the project dependencies, but maybe due to the older `ca-certificates-java` that comes with the Ubuntu 16.04 LTS ec2 AMI (the apt package version is `20160321ubuntu`) ... does that make any sense @technomancy ?

**Comment by blak3mill3r** [comment]
I saw evidence that `clojars.org` was intermittently unavailable today (couldn't pull deps locally) around the time I posted the messages above. I upgraded `lein` on the ec2 instance back to `2.8.1` and everything works fine. My theory now is that somehow the fact that `clojars.org` was on the blink caused this error message, I am pretty confident that is the case since I did not change anything and `2.8.1` has no such problem when I tried it just now.

**Comment by danielcompton** [comment]
Our monitoring for Clojars didn't show anything, but depending on network routing, and the length of the outage, our probes may not have picked it up.

**Comment by blak3mill3r** [comment]
Good point... it could easily have been local to my office network... but if a local network hiccup interfering with Clojars can cause `lein` to emit this warning, that would be misleading, so I wanted to document my experience here in case it helps others avoid a rabbit hole.

I am pretty confident it was some transient issue, because the same `project.clj` on the same EC2 instance with the same `lein` version worked fine a couple hours later.

**Comment by technomancy** [comment]
An outage or network blip would not cause this error message.

Most likely what happened is that Leiningen 2.8.1 refused to download the dependency, and then Leiningen 2.7.1 downloaded it, and then Leiningen 2.8.1 saw that the dependency was already downloaded, and so it didn't need to try to connect to the repo to get it. Removing the cached copy would cause the problem to come back.

> I believe that means it is a transitive dependency of the project that's at fault.

Yes, that's accurate.

I realized there's a way to get better debugging info here; it's to set the HTTP wagon to a reified `Wagon` instance which intercepts the calls to find out what the URL and artifact id before aborting. However the docs on this are a bit hairy and it's not particularly straightforward.

**Comment by timmc-bcov** [comment]
I've been looking at the docs for Wagon (of *some* version, not necessarily the right one) and I have no idea which one I would be able to override with proxy to get that info: https://maven.apache.org/wagon/apidocs/org/apache/maven/wagon/Wagon.html

**Comment by timmc-bcov** [comment]
OK, stick this at the top of your project.clj and move your .m2 elsewhere temporarily:

```
(require 'cemerick.pomegranate.aether)
(cemerick.pomegranate.aether/register-wagon-factory!
 "http"
 #(proxy [org.apache.maven.wagon.providers.http.HttpWagon] []
    (get [^String res ^java.io.File f]
      (println "HTTP Wagon get:" res "from" f)
      (proxy-super get res f))))
```

The output is gonna be interleaved and nasty, but it should tell you what you need to know.

**Comment by technomancy** [comment]
Spoke too soon; I was able to reify the needed methods and emit a helpful message:

```
Tried to use insecure HTTP repository without TLS:
 myprivate: http://technomancy.us/repo
 org/ow2/proactive/process-tree-killer/1.0.0/process-tree-killer-1.0.0.pom 
 
This is almost certainly a mistake; for details see 
https://github.com/technomancy/leiningen/blob/master/doc/FAQ.md
```

**Comment by technomancy** [comment]
@timmc-bcov oops; missed your message there. Proxying the HTTP wagon would probably have been a bit simpler than reifying the interface.

@blak3mill3r I would recommend moving your `~/.m2` directory out of the way and running `lein deps` from master if you want to be able to identify the offending dependency and send them a bug report.

**Comment by blak3mill3r** [comment]
Excellent. Thank you.
