### ISSUE TITLE
lein self-install error on Windows

### ISSUE THREAD

**Issue by pedro-w** [technomancy/leiningen#2412]
I tried to install leiningen 2.8.1 on Windows 10 64-bit. I don't have wget or curl installed so the batch file used PowerShell to fetch the jars. I got the following error - of which I think "Could not create SSL/TLS secure channel" is the significant part.

```
>lein self-install
Downloading Leiningen now...
Exception calling "DownloadFile" with "2" argument(s): "The request was
aborted: Could not create SSL/TLS secure channel."
At line:1 char:145
+ ... che]::DefaultNetworkCredentials; $client.DownloadFile($a, $f)} "https ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException


Failed to download https://github.com/technomancy/leiningen/releases/download/2.8.1/leiningen-2.8.1-standalone.zip

It is possible that the download failed due to "powershell",
"curl" or "wget"'s inability to retrieve GitHub's security certificate.
The suggestions below do not check certificates, so use this only if
you understand the security implications of not doing so.

The PowerShell failed to download the latest Leiningen version.
Try to use "curl" or "wget" to download Leiningen by setting up
the HTTP_CLIENT environment variable with one of the following
values:

  a) set HTTP_CLIENT=wget --no-check-certificate -O
  b) set HTTP_CLIENT=curl -f -L -k -o

NOTE: Make sure to *not* add double quotes when setting the value
      of HTTP_CLIENT
```

**Comment by pedro-w** [comment]
I was able to fix it by specifying the security protocol, see below. Please let me know if this is useful and I will submit it as a github PR.

```patch
--- lein.bat.original   2018-04-09 11:27:07.549354500 +0100
+++ lein.bat    2018-04-09 11:28:43.442263400 +0100
@@ -154,7 +154,7 @@
 call powershell -? >nul 2>&1
 if NOT ERRORLEVEL 0 goto TRY_WGET
     set LAST_HTTP_CLIENT=powershell
-    powershell -Command "& {param($a,$f) $client = New-Object System.Net.WebClient;  $client.Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials; $client.DownloadFile($a, $f)}" ""%2"" ""%1""
+    powershell -Command "& {param($a,$f) $client = New-Object System.Net.WebClient; [Net.ServicePointManager]::SecurityProtocol = 'tls12' ; $client.Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials; $client.DownloadFile($a, $f)}" ""%2"" ""%1""
     SET RC=%ERRORLEVEL%
     goto EXITRC
```

**Comment by scottdw** [comment]
I ran into the same issue and the fix provided by @pedro-w worked for me.

**Comment by shjanken** [comment]
@pedro-w It's worked for me

**Comment by winks** [comment]
Thanks, @pedro-w - I'm gonna try if this still works on Win7 and then merge it.

**Comment by pedro-w** [comment]
Cool, thanks. As a matter of interest, do you know what has changed? It definitely used to work, but I don't tend to use Windows for clojure and I hadn't attempted an update for a while.

**Comment by winks** [comment]
No clue, sorry - I don't use Win10 at all and only do clojure on Windows very rarely, mostly to investigate bug reports tbh :)

**Comment by pedro-w** [comment]
I haven't got Win7 to test. What error do you get? Also, what version of Powershell comes installed with Windows 7?

    powershell -command "$PSVersionTable.PSVersion"

I've got 5.1.16299.251 on mine. 

But I think it might be a certificate thing - which I never have understood properly...

**Comment by winks** [comment]
So afaik it went like this:
  * GitHub disabled TLS 1.1 2 months ago: https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/ 
  * Win7 can only do `[Ssl3, Tls]` (I assume Tls == TLS 1.1)

My Powershell is 
PS C:\Users\Florian> echo $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1

**Comment by winks** [comment]
OK, the proposed fix also works on at least `Windows 8.1 with PowerShell 4`.
I'd need someone with PowerShell 3 now to test this snippet:
```
$client = New-Object System.Net.WebClient; [Net.ServicePointManager]::SecurityProtocol = 'tls12' ; $client.Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials; $client.DownloadFile("https://github.com/technomancy/leiningen/releases/download/2.8.1/leiningen-2.8.1-standalone.zip", "foo.zip");
```

My current plan (which might change until tomorrow, meh) is to add a check like

```
if (($PSVersionTable.PSVersion | Select-Object -ExpandProperty Major) -lt 4)  { Write-Host "Please upgrade your powershell version" }
```
and maybe try `curl/wget` in the PATH before that

**Comment by winks** [comment]
Also this looks totally hacky but it seemed to work: https://superuser.com/a/536400

Also I found some numbers that there might be 40% Win10, 40% Win7 and supposedly 20% Win 8, so breaking Win7 at the expense of Win10 isn't a good tradeoff. (Although of course it will slowly roll over for at least 10-20% in the next 1-2 years I guess)

**Comment by winks** [comment]
It might have "broken Win7" in a sense when you use .net and/or IE maybe.
I have a Win7 workstation at home and while using Chrome/Firefox and not doing any development where I don't use libcurl or something like that... I hadn't even noticed.

**Comment by winks** [comment]
OK, so #2405 is basically the same as the fix by @pedro-w - I totally missed that it was merged, sorry.
Until it gets released though, manual patching :(

I prepared a PR #2418 that will change nothing for Win10, just give a somewhat reasonable error message for people whose PS is too old.

Only TODO now: Test on Win 8.0 and Win 8.1 so I can change the version check if needed

**Comment by winks** [comment]
Tested Win8.1 via one of those free MS IE test VMs and PS4 does indeed work with TLS 1.2

**Comment by pedro-w** [comment]
Sorry, I missed #2405 too; I only looked in open issues. Thanks @winks and everyone for your support on this!

**Comment by winks** [comment]
My Win7 box acted up yesterday, I'll have another look at #2211 (hopefully before the weekend) and then we'll try to release 2.8.2 soon which should unbreak Win10+8.1 and at least show an actionable error for 7+8. Stay tuned :)

**Comment by arrjayH** [comment]
This fixed worked for me, thanks!

**Comment by stevemk14ebr** [comment]
This fix works, please PR

**Comment by winks** [comment]
Seems we're blocked by #2443 but we'll try to get a release out after that, sorry for the wait.

**Comment by stelamelo** [comment]
The fix worked for me too! thanks!

**Comment by winks** [comment]
@technomancy It's been a while but I'm pretty sure someone on irc told me (maybe even you) that we can't cut a new release because of #2443 - so fwiw it's worth ignore anyting *I* wrote about blocking, I am pretty sure I was just relaying info I got somewhere, may it have been correct at the time or not. 
Nothing related to SSL should block any release, I just had a lot to test with Win7 vs 8 vs 10 back then.

**Comment by technomancy** [comment]
@winks thanks; I just meant is there some reason this issue is still open? Is it fixed on master and left open so it's easier to find for folks who are running 2.8.1?

**Comment by winks** [comment]
Should be fixed on master, yes. So we can close it, but I think it's indeed more visible for current users on Windows.

**Comment by technomancy** [comment]
OK. I'm trying to make sure everything we need is fixed for the next version, so I'm going to close this out.

**Comment by technoanga** [comment]
Hello,
I want to use clojure on windows 10,but when I type lein repl on terminal it gives error--
Could not transfer artifact nrepl:nrepl:jar:0.6.0 from/to central (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.196.209] failed: Connection timed out: connect
Could not transfer artifact nrepl:nrepl:jar:0.6.0 from/to clojars (https://repo.clojars.org/): Connect to repo.clojars.org:443 [repo.clojars.org/151.101.165.128] failed: Connection timed out: connect
Could not transfer artifact clojure-complete:clojure-complete:jar:0.2.5 from/to central (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.196.209] failed: Connection timed out: connect
Could not transfer artifact clojure-complete:clojure-complete:jar:0.2.5 from/to clojars (https://repo.clojars.org/): Connect to repo.clojars.org:443 [repo.clojars.org/151.101.165.128] failed: Connection timed out: connect
Could not transfer artifact nrepl:nrepl:pom:0.6.0 from/to central (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.52.209] failed: Connection timed out: connect
Could not transfer artifact clojure-complete:clojure-complete:pom:0.2.5 from/to central (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.196.209] failed: Connection timed out: connect
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Could not resolve dependencies

Can anyone help me with this,as I am a beginner to Clojure

**Comment by wrkelly** [comment]
Having the same problem but these fixes aren't resolving.

C:\>lein self-install
Downloading Leiningen now...
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:1 char:324
+ ... che]::DefaultNetworkCredentials; $client.DownloadFile($a, $f); }} "ht ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException


Failed to download https://github.com/technomancy/leiningen/releases/download/2.9.6/leiningen-2.9.6-standalone.zip

It is possible that the download failed due to "powershell",
"curl" or "wget"'s inability to retrieve GitHub's security certificate.

The PowerShell failed to download the latest Leiningen version.
Try to use "curl" or "wget" to download Leiningen by setting up
the HTTP_CLIENT environment variable with one of the following
values:

  a) set HTTP_CLIENT=wget -O
  b) set HTTP_CLIENT=curl -f -L -o

NOTE: Make sure to *not* add double quotes when setting the value
      of HTTP_CLIENT
