### ISSUE TITLE
Project's `:release-tasks` do not override user-specific ones

### ISSUE THREAD

**Issue by xiongtx** [technomancy/leiningen#2438]
## Expected behavior

`:release-tasks` of the project profile should _override_ those of the user profile.

The [section on profiles](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md#declaring-profiles) says:

> User-wide profiles can also be specified in `~/.lein/profiles.clj`. These will be available in all projects managed by Leiningen, though those profiles will be overridden by profiles of the same name specified in the project. 

## Actual behavior

Release tasks in the user profile are _appended_ to those of the project profile.

## Steps to reproduce

1. Create a new project: `lein new release-test`
2. Add some step to `:release-tasks` in `project.clj`
   - E.g. `:release-tasks [["version"]]`
3. Add some other step to `:release-tasks` in `~/.lein/profiles.clj`
   - E.g. `{:user  {:release-tasks [["deps" ":tree"]]}}`
4. Run `lein release`   
5. See that both the project-specific `:release-tasks` are executed first, then the user `:release-tasks`

## Versions

- Lein : `2.8.1`
- Clojure: `1.8.0`
- Java: `1.8.0_172`

**Comment by technomancy** [comment]
> The section on profiles says:
>
>  User-wide profiles can also be specified in
>  ~/.lein/profiles.clj. These will be available in all projects managed
>  by Leiningen, though those profiles will be overridden by profiles of
>  the same name specified in the project.

This is misleading; instead of saying they're overridden it should say
the ones in the project will take precedence. Taking precedence in the
case of scalar values means replacing them, but in the case of composite
values it means the ones with precedence will go first.

> Release tasks in the user profile are appended to those of the project profile.

Putting release tasks in the user profile is very strange and almost
certainly a mistake since the method used to release is very
project-specific and needs to be specified in project.clj.

But the wording could be clearer.
