### ISSUE TITLE
Publish to SDKMAN too!

### ISSUE THREAD

**Issue by aadrian** [technomancy/leiningen#2499]
Please trigger the publish of v2.8.2 to SDKMAN too !
https://sdkman.io/sdks

Thank you.

**Comment by sarevok-anchev** [comment]
+1

**Comment by technomancy** [comment]
Thanks, but this bug tracker is for issues with Leiningen, not for 3rd-party distributions.

**Comment by marc0der** [comment]
This is in fact an issue on your side so please consider re-opeing this issue.

Sometime ago I issued API credentials to your team for publishing to SDKMAN via our [Vendor API](https://sdkman.io/vendors). Only one version was ever published, namely _2.7.1_. Since then, the archives have been completely inconsistent and don't follow the standard SDK archive format (with `bin` folder etc) like all other Java/JVM SDKs do.

I would like to see the archives built in a consistent manner, and secondly would love to see you publishing all your releases to SDKMAN as _many_ people are asking for them.

You have a great piece of software here, and I'm giving you a free channel to distribute it. Remember that SDKMAN is completely free and open source. I'd love to help you get this going again. Please shout if I can help in any way to make it happen.

**Comment by technomancy** [comment]
> Sometime ago I issued API credentials to your team for publishing to SDKMAN via our [Vendor API](https://sdkman.io/vendors). Only one version was ever published, namely _2.7.1_.

If someone wants to volunteer to take on the packaging duties for SDKMAN
that's great. I don't know who it was that published 2.7.1 but it would
seem that they are no longer interested in keeping up with that.

But packaging scripts for SDKMAN should be tracked in a separate repo
just the same as we do with the packaging for every other system.
Debian, Homebrew, Arch, etc, all keep their packaging in a repo
administered by the packaging team.

**Comment by marc0der** [comment]
For more background about what happened, you can trace it back in issue #2204.

**Comment by winks** [comment]
Sorry, this took a little longer, but 2.9.0 is now on sdkman and we should be able to do this close to the release in the future - https://github.com/leiningen/leiningen-sdkman

**Comment by aadrian** [comment]
@wilkes thank you very much. This looks great! The chocolatey version is also very useful !

**Comment by technomancy** [comment]
Nice work! Any chance we could get `bin/lein-skdman` into that repo too as per https://github.com/technomancy/leiningen/issues/2346 ?

**Comment by winks** [comment]
Yes, tracked at https://github.com/leiningen/leiningen-sdkman/issues/1 - but I think we should doublecheck that `lein` and `lein-sdkman` didn't converge too much, that will be a bit of work. Right now I fear it will drift even further if it's spun out.

**Comment by technomancy** [comment]
It might be best if the sdkman repo contains a patch which gets applied to the upstream `bin/lein` script instead? That way you get most of the changes for free, and if there is a conflict then the patch won't apply and you should notice. That's the strategy that Debian takes.

**Comment by marc0der** [comment]
@winks Thanks so much for getting it out there for everyone to use. Great work!
