### ISSUE TITLE
Can't execute clojure code in lein REPL in bash on windows

### ISSUE THREAD

**Issue by alexamy** [technomancy/leiningen#2553]
Can't execute code in lein REPL when using Git Bash (MinGW64) on Windows. Pressing 'Enter' just adds newlines. Only MinGW terminal is affected, when I'm using bash terminal in Visual Studio Code, everything works fine. 

**To Reproduce**
1. Start bash terminal. I'm using `Git Bash here` from explorer context menu.
2. Run the command `lein repl`
3. Try to enter some clojure code. By pressing 'enter' you just add newlines (and you can type other symbols), but the code isn't executed.

**Expected behavior**
Expected to run the entered code after pressing 'enter' key.

**Environment**
- Leiningen Version: 2.9.1.
- Leiningen installation method: manual, by copying `lein` script.
- JDK Version: 1.8.0_121.
- OS: Windows 7.
- MinGW64.

**Comment by MigrenusMaximus** [comment]
Pressing Enter before the terminating parentheses of the outermost form produces newlines. Could be an issue with Git Bash on Windows preventing the REPL from detecting the cursor is at the end.
Try using CTRL+Enter as a workaround in the meantime.

**Comment by mhavrlent** [comment]
You have to install winpty (`pacman -S winpty`) and then run: `/usr/bin/winpty lein.bat repl`
(I'm using full path to winpty because I have another winpty in "Git for windows" installation dir and it's on my PATH since "Git for windows" handles line endings better than msys2 git).

You can then set alias in your ~/.bashrc like this:
`alias repl='/usr/bin/winpty lein.bat repl'`  (don't forget to do `source ~/.bashrc` afterwards in your current terminal or restart your terminal)
Once you have the alias, simply run repl with `repl`.

**Comment by technomancy** [comment]
I don't think there's anything we can do about these types of issues, but if there is we can reopen this.
