### ISSUE TITLE
Leiningen dependencies interfer with dependencies of plugins

### ISSUE THREAD

**Issue by dirk-wetzel-otm** [technomancy/leiningen#2595]
Plugins can't have a different version of a dependency if leiningen itself uses a different version of that dependency.

Specific example: I updated one of our plugins to use the following method within the library `[commons-codec "1.12"]`:
```
org.apache.commons.codec.binary.Hex#encodeHexString(byte[], boolean)
```
That specific method is not available in older versions of the library, such as version **1.9** which is a transitive dependency in leiningen.  
Trying to use that plugin failed, because that method doesn't exist in the version of the library that is loaded by leiningen.

Since it's our own plugin, we could change it as needed. But in general plugins should not be restricted in the library versions that they can use.

If there is a way to avoid that, that I don't know of, please let me know.

---

**Way to reproduce**
1. Create an empty leiningen project (f.e. `lein new app test`)
2. Add these lines to the project.clj:  
```
  :pedantic? :warn
  :plugins [[commons-codec "1.12"]]
```
3. Run any lein command, f.e. `lein deps`

---

**Actual behavior of reproduction steps**
The following warning is printed, signalling that a different library version is used than was intended by _project.clj_
```
Tried to load commons-codec version 1.12 but 1.9 was already loaded.
```

**Expected behavior**
When following the steps to reproduce, `[commons-codec "1.12"]` should be loaded and nothing should be printed out.

---

**Environment**
- Leiningen Version:2.9.1
- Leiningen installation method: manual
- JDK Version: openjdk version "11.0.2" 2019-01-15
- OS: Ubuntu 18.04.2

**Comment by technomancy** [comment]
Unfortunately we are stuck with this behavior; Leiningen and its dependencies must be loaded in the bootstrap classloader in order to reduce startup time, and bytecode on the bootstrap classloader cannot be shadowed by newly-loaded bytecode.

However, if you want to sacrifice startup time in order to get compatibility you can try setting the environment variable `LEIN_USE_BOOTCLASSPATH=no`. You will still get the warning, but it should be able to load new dependencies that replace the ones that come with Leiningen.

**Comment by dirk-wetzel-otm** [comment]
That's unfortunate. So the solution would be making leiningen entirely free of dependencies, which probably isn't worth the effort.

Thank's for pointing out the environment variable, that should already help a lot :)
