### ISSUE TITLE
:jar-exclusions ignored at profiles.clj level

### ISSUE THREAD

**Issue by dpippert** [technomancy/leiningen#2644]
I would like :jar-exclusions to take, when stationed at your profiles.clj level, such as:

{:user {:plugins      [[lein-pprint "1.1.2"]]
          :jar-exclusions [#"\.swp$"]}}

There are some files used by editors and such that I would never want to be part of my jar. Putting these exclusions at the project.clj level confuses other team members that are not aware what editor, for example, is being used by some developers. Plus making :jar-exclusions only valid at the project.clj level clutters project.clj in these cases.

**Comment by technomancy** [comment]
The fact that the user profile is ignored during jar creation is intentional. It's very important that creating a jar is 100% repeatable no matter what machine it's run on. It's better to be over-cautious and put things in your project.clj than to open it up for the possibility that you'd get one jar on one machine and another jar on another machine.
