### ISSUE TITLE
2.9.3 seems to have broken the modules plugin

### ISSUE THREAD

**Issue by lkonstantinov** [technomancy/leiningen#2671]
Hi,

I've a multimodule project that was happily building with GitHub actions until today. It looks like their OS image picked up lein 2.9.3 which seems to have broken the "_" version resolution used by the modules (https://github.com/jcrossley3/lein-modules) plugin

```
------------------------------------------------------------------------
Retrieving com/fasterxml/jackson/core/jackson-core/2.9.9/jackson-core-2.9.9.jar from central
Could not find artifact instaparse:instaparse:jar:_ in central (https://repo1.maven.org/maven2/)
Error encountered performing task 'install' with profile(s): 'dev-core-parent,provided-core-parent,inherited-core-parent,base,system,user'
Could not find artifact instaparse:instaparse:jar:_ in clojars (https://repo.clojars.org/)
Could not find artifact cheshire:cheshire:jar:_ in central (https://repo1.maven.org/maven2/)
Could not find artifact cheshire:cheshire:jar:_ in clojars (https://repo.clojars.org/)
Could not find artifact com.github.ben-manes.caffeine:caffeine:jar:_ in central (https://repo1.maven.org/maven2/)
Could not find artifact com.github.ben-manes.caffeine:caffeine:jar:_ in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
```

Reverting back to 2.9.1 makes the problem go away.

Just FYI - the previous time this happened it was related to #2212

**Comment by glts** [comment]
This is caused by #2593 (mea culpa). The gist is that profiles are evaluated earlier, too early for lein-modules it seems.

If you look at the commit message and the linked issues, you’ll see that that change addressed several long-standing and often-complained-about problems. I did not expect to break middleware, but then again middleware can do anything and so can be impacted by this change.

Now I don’t know what the best resolution is. The breakage is bad, but it is also a pity to reintroduce all the issues mentioned above. Could the lein-modules middleware be adapted?

**Comment by technomancy** [comment]
I think glts is right; reverting this would probably cause more problems than it solves.

**Comment by jaor** [comment]
so, does this mean that if we use the modules plugin we'll have to stick
to leiningen < 2.9.3 forever? or is this fixable in the plugin?

thanks!

**Comment by technomancy** [comment]
No, I just meant that the fix should be tracked in the plugin's issue tracker rather than here.
