### ISSUE TITLE
Add instructions for on-prem installation

### ISSUE THREAD

**Issue by billallen256** [technomancy/leiningen#2710]
Not all development happens where there's an Internet connection.  It would be great to see some instructions about how to install and use Leiningen in on-prem environments.

**Comment by technomancy** [comment]
In the tutorial it explains that you can explicitly tell Leiningen to download your dependencies (when you are online) using the `lein deps` command. Then they will be available when you go offline.

Do you have something more specific in mind here?

**Comment by gershwinlabs** [comment]
Sorry I wasn't clear.  I meant on-prem and never connected to the Internet, where only the Leiningen source and Clojure compiler are available.

**Comment by technomancy** [comment]
Sorry, are you asking how to download dependencies without any internet connection? I still don't understand the question.

**Comment by gershwinlabs** [comment]
The first thing Leiningen does is download from the Internet, but on a network without an Internet connection, the dependencies have to be copied over manually.  What dependencies need to be copied over to build Leiningen from source?

**Comment by technomancy** [comment]
You could hypothetically build Leiningen on a machine connected to the internet, then copy over `~/.m2` to the disconnected machine and build it again there, but it's much easier to copy the single self-install jar file from `~/.lein/self-installs` instead for the version you're interested in using.

But even once you have Leiningen installed on a machine with no internet access, it will not be very useful because you can't use it to download the dependencies of whatever project it is you're working on. Copying `~/.m2` again from a machine that does have those dependencies already downloaded would solve that problem, (which you would have to repeat every time you changed the dependencies) but it's difficult to understand what it is that you're hoping to accomplish here.

**Comment by technomancy** [comment]
If you have a more specific question we can reopen this but I don't think that the issue in its current state is actionable.
