### ISSUE TITLE
shasum question

### ISSUE THREAD

**Issue by reutsharabani** [technomancy/leiningen#2732]
Currently if you change the lein version to get a different version you need to find the correct shasum digest. I couldn't find where shasums are published for the specific way the lein script validates so I downloaded the lein asset myself and added the shasum manually. Any chance the expected shasums can be published with releases? It could be in github releases I'm just unsure where to find it: https://github.com/technomancy/leiningen/releases

**Comment by technomancy** [comment]
Yeah, we could definitely set this up, but it's easier to use `lein
downgrade 2.9.0` or whatever version you want. Editing the shell script
directly isn't really recommended because the shell script changes
between versions, and you want to make sure that the script version
matches the uberjar you're using.

**Comment by reutsharabani** [comment]
I totally missed lein downgrade (I now see there is an alias mentioned in the end of the help text). thanks!
