### ISSUE TITLE
Lein repl failed caused by: java.lang.ClassNotFoundException: jdk.javadoc.doclet.Doclet

### ISSUE THREAD

**Issue by igajsin** [technomancy/leiningen#2785]
Hi, 

there is a problem when I try to use leiningen on Gnu Guix. I believe something wrong with my setup, but I quite new in all: lein, clojure, java and guix worlds, so I need some help to mitigate the issue. 

If I create a complete new project  with `lein new app my-stuff ` and then `cd my-stuff; lein repl` I receive an [error](https://paste.debian.net/1227713/).

Versions are:
```
$ lein version
Leiningen's classpath: :/gnu/store/h7kg2h67ifa3m90gc7cfgdqj2h9myk7m-leiningen-jar-2.9.8/share/leiningen-standalone.jar
Applying task version to []
Leiningen 2.9.8 on Java 17.0.1 OpenJDK 64-Bit Server VM

$ java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+0-adhoc..source)
OpenJDK 64-Bit Server VM (build 17.0.1+0-adhoc..source, mixed mode, sharing)

$ clj --version
rlwrap: warning: could not set locale
warnings can be silenced by the --no-warnings (-n) option
Clojure CLI version 1.10.3.1040
```

Please, don't hesitate to ask if I can provide more data.

**Comment by winks** [comment]
I just had a brief look via

```
wget https://github.com/technomancy/leiningen/raw/2.9.8/bin/lein
chmod +x lein
docker run -it --rm -v "$PWD:/mnt" -v "$PWD/m2:/root/.m2" openjdk:17.0-jdk /bin/bash
```

```
cd /mnt
./lein ...
```

so there doesn't seem to be a general problem with Java 17 (which isn't too common I guess).

Unfortunately I don't even have any wild guesses to the reason right now. Could you maybe try a different JDK on guix? 11 or 8, if they have that.

**Comment by technomancy** [comment]
The error you posted comes from Cider, so perhaps you should open a bug report on their tracker: `Syntax error compiling at (cider/nrepl/inlined_deps/orchard/v0v6v5/orchard/java/parser.clj:1:1).`

**Comment by igajsin** [comment]
Strange. That happened in CLI without cider. I'll try to delete cider and check what will happen after that.

**Comment by igajsin** [comment]
I've switched to icedtea
```
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (IcedTea 3.19.0) (guix build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```
and at first glance lein works properly. Tomorrow I can test it better.

**Comment by technomancy** [comment]
Sounds like this is no longer a problem? We can reopen if more debugging is needed.

**Comment by Archenoth** [comment]
So, the problem, for future reference, seems to be that some distributions of JDK seem to be removing (???) doclet classes to make themselves lighter. Like, [this class](https://docs.oracle.com/en/java/javase/17/docs/api/jdk.javadoc/jdk/javadoc/doclet/Doclet.html) just seems to not exist reliably depending on where your Java originated from, even if it's a version that should have it typically

A couple examples seem to include Guix, and IBM's Semeru Runtimes (And many other similar docker JDK distributions)

As a result, [orchard seems to be suffering](https://github.com/clojure-emacs/orchard/issues/152#issuecomment-1040846731), which cascades down to a pretty massive amount of Emacs Clojure tooling

In some cases, you can install the missing pieces of the JDK, but in the case of docker containers, the installations aren't actually from a package manager, and you can't install it with maven since, I mean, why would you ever be lacking something that's a documented and stable part of the JDK?

**Comment by technomancy** [comment]
It sounds like it would be best to report this to Orchard's issue tracker then? I don't know if they'll be able to work around the problem, but perhaps at least they can give a more useful error message that would point people to the root cause of the problem.

**Comment by Archenoth** [comment]
Yep! I'm in the process of doing that~ Though they already (very reasonably) stated that running on incomplete JDKs wasn't really something that was really a case they really gave much thought.

I just noticed this issue while looking around for other places it showed up, and this just seemed to be disconnected enough that I figured I'd give a little extra context so you weren't 100% in the dark in the meantime! (Since you might see this problem a few times)
