### ISSUE TITLE
repl :headless does not work without stdin.

### ISSUE THREAD

**Issue by kenrestivo** [technomancy/leiningen#715]
``` shell
lein2 repl :headless &
```

stops and does not run.

but

``` shell
nohup lein2 repl :headless &
```

works fine, as does

``` shell
lein2 repl :headless < /dev/null  &
```

or

```
$ lein2 repl :headless
^Z
[1]+  Stopped                 lein2 repl :headless
$ bg
[2]+ lein2 repl :headless &
```

Looks like the JVM expects stdin and won't background without it.

**Comment by kyle-laracey** [comment]
I am having this same issue, I've posted the details in a [question on Stackoverflow](https://stackoverflow.com/questions/44345899/running-lein-repl-headless-in-the-background). 

It's not clear to me what `stty stop ''` would have to do with this. Flow control (AFAIK) is not related to job control and controlling terminals, which seems to be the issue here - lein is receiving SIGTTIN.

**Comment by kenrestivo** [comment]
Good point.  I never really figured out what the problem was; just hacked around it by doing:

```sh
lein trampoline repl :headless < /dev/null &
```

which works.

A colleague at work has modified my build scripts commands to be:

```sh
echo | lein uberjar
```

and this seems to at least be able to keep Jenkins happy.

**Comment by kyle-laracey** [comment]
My question on StackOverflow was answered; `lein trampoline repl :headless &` seems to work for me. I think this is somehow related to https://github.com/technomancy/leiningen/issues/957 and https://github.com/technomancy/leiningen/issues/1173 but I don't quite understand how those issues were resolved. Thanks.
