### ISSUE TITLE
Ordering of java/clojure compilation

### ISSUE THREAD

**Issue by bartosz-k** [technomancy/leiningen#847]
The only place where java/clojure compilation is mentioned is here:

``` clojure
(defproject megacorp/superservice "1.0.0-SNAPSHOT"
  :description "A Clojure project with a little bit of Java sprinkled here and there"
  :min-lein-version  "2.0.0"
  :source-paths      ["src/clojure"]
  :java-source-paths ["src/java"])
```

But I don't know the order of compilation, what if i want to compile some java, then some clojure and then again java? How can I achieve it? Is far I know the best answer match in other technologies of my question are goals in Maven.

**Comment by matanster** [comment]
I wonder how does my use case merge here, as it is differently specific compared to the beaver use case, yet falls under the same issue title of interleaving clojure and java code:

I am writing a clojure library to be used by both clojure and Java applications. In order to have proper tests for my library, the library project includes a Java source file that uses the clojure code, so that usage from Java is part of the library's test suite.

Obviously, it is not obvious how to manage a smooth compilation graph here, such that the Java code can access the clojure library's code, _and be run as part of the project's test suite_. Apparently, the following compilation sequence should take place:

1. java Interface definitions for making the code usable from Java
2. clojure code implementing the library and those java interfaces
3. the java source file/s which test the library

Is there anything in leiningen to support specifying such an interleave?

**Comment by technomancy** [comment]
> 1 java Interface definitions for making the code usable from Java 
> 2 clojure code implementing the library and those java interfaces 
> 3 the java source file/s which test the library 

This might work:

    $ lein do javac, with-profile +test javac, test

Keep the source for #3 above in the test-java-src/ dir, and include that `:java-source-paths` entry in the `:test` profile.

You can add this to streamline things:

    :aliases {"test" ["do" "javac," "with-profile" "+test" "javac," "test"]}

**Comment by matanster** [comment]
Thanks @technomancy this looks promising and I've learned about various ways of using profiles now. One thing I'm still after is making the clojure namespaces of my project available to the Java code being run/compiled from the suggested `test-java-src` dir. It seems that Java source fails to find the namespace compiled from my clojure code, resulting in a "package does not exist" error.

So I am not yet sure how the classpath is managed across separately running (as in `lein do`) tasks, but hopefully will figure it out.

**Comment by matanster** [comment]
Well I learn that AOT should be used to allow the use of clojure code from Java code within the same project, but I bump into a potential clojure/lein issue as it looks like compilation gets broken under the hood:

```
$ lein compile
Compiling org.boteval.samples.driver
java.lang.ClassNotFoundException: java.lang., compiling:(org/boteval/samples/driver.clj:1:1)
```

There's nothing in the [source code I have](https://github.com/matanster/boteval-fiddle/blob/4714a1d8d8924bb68513bb393589ca38c8e2a187/src/clojure/org/boteval/samples/driver.clj) that explicitly nor implicitly leads the compiler to seek the bogusly truncated class `java.lang.`

Maybe that's time to take my interop adventures elsewhere...

**Comment by matanster** [comment]
Well, my problem was with AOT compilation alone, [in my case](http://dev.clojure.org/jira/browse/CLJ-1622?focusedCommentId=45307#comment-45307). I will post my working java sandwiching example if anyone cares.

**Comment by matanster** [comment]
Thanks @technomancy for the assistance:
My solution, using aliases for hooking up clojure and java tests without introducing compile-time dependency between them:

```
(defproject boteval "0.1.0-SNAPSHOT"
  :description "the boteval framework"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :min-lein-version "2.0.0"
  :source-paths      ["src/clojure"]
  :java-source-paths ["src/java"]
  :javac-options     ["-target" "1.8" "-source" "1.8"]
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :aot [org.boteval.samples.driver]
  :profiles {:java-tests-compile
    {:java-source-paths ["src/java-test"]}}
  :aliases {
    "java-tests" ["do" "compile," "with-profile" "+java-tests-compile" "javac," "run" "-m" "org.boteval.javaSamples.JavaUsageTest"]
    "all-tests" ["do" "test," "java-tests"]
  }
  :main org.boteval.core)

```

I avoided the extra compile-time dependency, because having leiningen compile my clojure tests code only _after_ my java test code ― such that my java test code could be called from my clojure tests ― is currently beyond me; I assume we cannot tease apart clojure tests compilation from clojure source compilation and make them separately scheduled phases. It would have been nice though if we could, as that will have implied we can arbitrarily arrange any order of compilation between Java and clojure sources ― addressing back the title of this thread. 

In case anything can be said about the last concern of freely mixing multiple clojure and java compilation steps that would be good to know for future cases!
