### ISSUE TITLE
`lein test` causes `macroexpand` and `macroexpand-1` to evaluate in a different manner?

### ISSUE THREAD

**Issue by mybuddymichael** [technomancy/leiningen#912]
`lein test` causes `macroexpand` and its partner to simply return their arguments.

`lein --version` is `Leiningen 2.0.0-preview10 on Java 1.6.0_37 Java HotSpot(TM) 64-Bit Server VM`

Given this test code:

``` clojure
(ns macrotest.core-test
  (:use clojure.test))

(defmacro foo []
  `(identity 1))

(deftest foo-test
  (is (= '(clojure.core/identity 1)
         (macroexpand-1 '(foo)))))
```

`lein test` results in this:

```
lein test macrotest.core-test

FAIL in (foo-test) (core_test.clj:8)
expected: (= (quote (clojure.core/identity 1)) (macroexpand-1 (quote (foo))))
  actual: (not (= (clojure.core/identity 1) (foo)))

Ran 1 tests containing 1 assertions.
1 failures, 0 errors.
```

In the nREPL:

```
macrotest.core-test=> (run-tests)

Testing macrotest.core-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
{:type :summary, :pass 1, :test 1, :error 0, :fail 0}
```

**Comment by emlyn** [comment]
I recently ran into the same problem, and couldn't find much about it other than this issue. After some investigation I think this isn't technically a bug, it's just the way Clojure works. It's to do with whether the code is executed from the same namespace or not. This can be demonstrated by adding a normal Clojure function to the test namespace in the OP, that just prints the macro expansion:
```clojure
(defn foo-fn []
  (println (macroexpand-1 '(foo))))
```
Then if you run it from the `user` namespace (or any ns other than `macrotest.core-test`), it prints out the unexpanded macro:
```bash
$ java -cp `(lein classpath)` clojure.main -e "(do (require 'macrotest.core-test) (macrotest.core-test/foo-fn))"
(foo)
```
But if you change to the `macrotest.core-test` namespace first, the macro gets expanded as expected:
```bash
$ java -cp `(lein classpath)` clojure.main -e "(do (require 'macrotest.core-test) (in-ns 'macrotest.core-test) (foo-fn))"
(clojure.core/identity 1)
```
This is because the macro name is quoted, so in another namespace it no longer refers to the macro, but is just a symbol with no binding. As a workaround, you could use a syntax quote instead: ``(macroexpand-1 `(foo))``, or you could add a fixture to the test namespace that rebinds the namespace during tests:
```clojure
(let [ns *ns*]
  (use-fixtures
    :once
    (fn [test-fn]
      (binding [*ns* ns]
        (test-fn)))))
```
